//! CRI v1 gRPC client for the rusternetes kubelet.
//!
//! This crate is the kubelet's southbound runtime backend: it speaks the
//! Kubernetes Container Runtime Interface (`runtime.v1`, gRPC) to a
//! CRI-conformant runtime such as containerd (which in turn drives an OCI
//! runtime like Youki). It replaces the Docker-API (bollard) coupling that tied
//! the kubelet to Podman/Docker.
//!
//! The generated gRPC types live under [`v1`]. Consumers should prefer the
//! domain-typed [`CriClient`] wrapper so the raw tonic surface stays isolated
//! and the backend can later be pointed at a Rust CRI server without touching
//! the kubelet.

use std::path::{Path, PathBuf};

use hyper_util::rt::TokioIo;
use tonic::transport::{Channel, Endpoint, Uri};
use tower::service_fn;

pub mod stream;

/// Generated CRI v1 protobuf/gRPC types (`package runtime.v1`).
///
/// The contents are machine-generated by tonic-build from the vendored proto;
/// lints are silenced because we do not own its style (doc formatting, large
/// enum variants, etc.).
#[allow(clippy::all, clippy::pedantic, clippy::nursery, rustdoc::all)]
pub mod v1 {
    tonic::include_proto!("runtime.v1");
}

use v1::image_service_client::ImageServiceClient;
use v1::runtime_service_client::RuntimeServiceClient;

/// Errors surfaced by the CRI client.
#[derive(Debug, thiserror::Error)]
pub enum CriError {
    /// Failed to establish the gRPC channel to the runtime socket.
    #[error("failed to connect to CRI socket {socket}: {source}")]
    Connect {
        socket: String,
        #[source]
        source: tonic::transport::Error,
    },

    /// A gRPC call returned an error status.
    ///
    /// Boxed: `tonic::Status` is large enough that carrying it inline trips
    /// clippy `result_large_err` on every `Result<_, CriError>`.
    #[error("CRI rpc {rpc} failed: {source}")]
    Rpc {
        rpc: &'static str,
        #[source]
        source: Box<tonic::Status>,
    },

    /// The socket path was not a valid endpoint.
    #[error("invalid CRI endpoint: {0}")]
    Endpoint(#[source] tonic::transport::Error),
}

/// Result alias for CRI operations.
pub type Result<T> = std::result::Result<T, CriError>;

/// A connected CRI v1 client.
///
/// Holds both the `RuntimeService` and `ImageService` clients over a single
/// shared [`Channel`] (cloning a tonic `Channel` shares the underlying
/// connection pool, so the two services do not open separate sockets).
#[derive(Clone)]
pub struct CriClient {
    runtime: RuntimeServiceClient<Channel>,
    image: ImageServiceClient<Channel>,
    socket: PathBuf,
}

impl CriClient {
    /// Connect to a CRI runtime listening on a Unix domain socket.
    ///
    /// `socket` is a filesystem path (e.g. `/run/containerd/containerd.sock`).
    /// The `unix://` URI scheme is accepted and stripped. tonic 0.12 rides
    /// hyper 1.x, so the tokio `UnixStream` is wrapped in [`TokioIo`] before the
    /// transport will accept it; the HTTP authority in the dummy URI is ignored
    /// because the custom connector dials the socket directly.
    pub async fn connect(socket: impl AsRef<Path>) -> Result<Self> {
        let socket = normalize_socket_path(socket.as_ref());
        let socket_for_conn = socket.clone();

        // The URI is a placeholder required by Endpoint; the connector below
        // ignores its authority and always dials the fixed socket path.
        let endpoint = Endpoint::try_from("http://[::]:50051").map_err(CriError::Endpoint)?;

        // Lazy connection: like bollard's `Docker` handle, the socket is dialed
        // on the first RPC, not here — so the kubelet can construct the runtime
        // at startup even if the CRI runtime is momentarily unavailable, and
        // recovers without a restart.
        let channel = endpoint.connect_with_connector_lazy(service_fn(move |_: Uri| {
            let path = socket_for_conn.clone();
            async move {
                let stream = tokio::net::UnixStream::connect(path).await?;
                Ok::<_, std::io::Error>(TokioIo::new(stream))
            }
        }));

        Ok(Self {
            runtime: RuntimeServiceClient::new(channel.clone()),
            image: ImageServiceClient::new(channel),
            socket,
        })
    }

    /// The socket path this client is connected to.
    pub fn socket(&self) -> &Path {
        &self.socket
    }

    /// Mutable access to the raw `RuntimeService` client.
    ///
    /// Later sub-projects (sandbox/container lifecycle, status, exec) build
    /// domain-typed methods on top of this; for now it is the escape hatch.
    pub fn runtime(&mut self) -> &mut RuntimeServiceClient<Channel> {
        &mut self.runtime
    }

    /// Mutable access to the raw `ImageService` client.
    pub fn image(&mut self) -> &mut ImageServiceClient<Channel> {
        &mut self.image
    }

    /// Perform the CRI `Version` handshake.
    ///
    /// The kubelet calls this at startup to confirm the runtime speaks CRI v1.
    /// `api_version` in the request is advisory; the response carries the
    /// runtime's name/version and the CRI API version it implements.
    pub async fn version(&mut self) -> Result<v1::VersionResponse> {
        let request = v1::VersionRequest {
            version: "v1".to_string(),
        };
        let response = self
            .runtime
            .version(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "Version",
                source: Box::new(source),
            })?;
        Ok(response.into_inner())
    }

    // ---- Image lifecycle (ImageService) ------------------------------------

    /// Pull an image, returning the runtime's canonical image reference.
    ///
    /// `runtime_handler` selects a runtime class (e.g. the Youki handler) for
    /// runtime-handler-scoped image stores; pass `None` for the default. The
    /// optional `sandbox_config` lets the runtime resolve registry settings from
    /// the owning sandbox — supplied when pulling on behalf of a specific pod.
    pub async fn pull_image(
        &mut self,
        image: &str,
        runtime_handler: Option<&str>,
        sandbox_config: Option<v1::PodSandboxConfig>,
    ) -> Result<String> {
        let request = v1::PullImageRequest {
            image: Some(v1::ImageSpec {
                image: image.to_string(),
                runtime_handler: runtime_handler.unwrap_or_default().to_string(),
                ..Default::default()
            }),
            auth: None,
            sandbox_config,
        };
        let resp = self
            .image
            .pull_image(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "PullImage",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().image_ref)
    }

    /// Look up an image's status; `None` if the runtime does not have it.
    pub async fn image_status(&mut self, image: &str, verbose: bool) -> Result<Option<v1::Image>> {
        let request = v1::ImageStatusRequest {
            image: Some(v1::ImageSpec {
                image: image.to_string(),
                ..Default::default()
            }),
            verbose,
        };
        let resp = self
            .image
            .image_status(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "ImageStatus",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().image)
    }

    // ---- Pod sandbox lifecycle (RuntimeService) ----------------------------

    /// Create and start a pod sandbox, returning its sandbox id.
    ///
    /// `runtime_handler` names the runtime class (e.g. the containerd handler
    /// wired to Youki); empty string selects the runtime default.
    pub async fn run_pod_sandbox(
        &mut self,
        config: v1::PodSandboxConfig,
        runtime_handler: &str,
    ) -> Result<String> {
        let request = v1::RunPodSandboxRequest {
            config: Some(config),
            runtime_handler: runtime_handler.to_string(),
        };
        let resp = self
            .runtime
            .run_pod_sandbox(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "RunPodSandbox",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().pod_sandbox_id)
    }

    /// Stop a running pod sandbox (idempotent on the runtime side).
    pub async fn stop_pod_sandbox(&mut self, pod_sandbox_id: &str) -> Result<()> {
        let request = v1::StopPodSandboxRequest {
            pod_sandbox_id: pod_sandbox_id.to_string(),
        };
        self.runtime
            .stop_pod_sandbox(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "StopPodSandbox",
                source: Box::new(source),
            })?;
        Ok(())
    }

    /// Remove a (stopped) pod sandbox and any remaining containers in it.
    pub async fn remove_pod_sandbox(&mut self, pod_sandbox_id: &str) -> Result<()> {
        let request = v1::RemovePodSandboxRequest {
            pod_sandbox_id: pod_sandbox_id.to_string(),
        };
        self.runtime
            .remove_pod_sandbox(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "RemovePodSandbox",
                source: Box::new(source),
            })?;
        Ok(())
    }

    /// Fetch a pod sandbox's status.
    pub async fn pod_sandbox_status(
        &mut self,
        pod_sandbox_id: &str,
        verbose: bool,
    ) -> Result<v1::PodSandboxStatusResponse> {
        let request = v1::PodSandboxStatusRequest {
            pod_sandbox_id: pod_sandbox_id.to_string(),
            verbose,
        };
        let resp = self
            .runtime
            .pod_sandbox_status(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "PodSandboxStatus",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner())
    }

    // ---- Container lifecycle (RuntimeService) ------------------------------

    /// Create a container in a sandbox, returning its container id. The
    /// container is created but not started — call [`Self::start_container`].
    pub async fn create_container(
        &mut self,
        pod_sandbox_id: &str,
        config: v1::ContainerConfig,
        sandbox_config: v1::PodSandboxConfig,
    ) -> Result<String> {
        let request = v1::CreateContainerRequest {
            pod_sandbox_id: pod_sandbox_id.to_string(),
            config: Some(config),
            sandbox_config: Some(sandbox_config),
        };
        let resp = self
            .runtime
            .create_container(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "CreateContainer",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().container_id)
    }

    /// Start a previously-created container.
    pub async fn start_container(&mut self, container_id: &str) -> Result<()> {
        let request = v1::StartContainerRequest {
            container_id: container_id.to_string(),
        };
        self.runtime
            .start_container(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "StartContainer",
                source: Box::new(source),
            })?;
        Ok(())
    }

    /// Stop a running container, giving it `timeout` seconds to exit before the
    /// runtime forcibly kills it.
    pub async fn stop_container(&mut self, container_id: &str, timeout: i64) -> Result<()> {
        let request = v1::StopContainerRequest {
            container_id: container_id.to_string(),
            timeout,
        };
        self.runtime
            .stop_container(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "StopContainer",
                source: Box::new(source),
            })?;
        Ok(())
    }

    /// Remove a (stopped) container.
    pub async fn remove_container(&mut self, container_id: &str) -> Result<()> {
        let request = v1::RemoveContainerRequest {
            container_id: container_id.to_string(),
        };
        self.runtime
            .remove_container(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "RemoveContainer",
                source: Box::new(source),
            })?;
        Ok(())
    }

    /// Update a running container's linux resource limits in place (in-place
    /// pod resize). `resources` carries the new cgroup values.
    pub async fn update_container_resources(
        &mut self,
        container_id: &str,
        resources: v1::LinuxContainerResources,
    ) -> Result<()> {
        let request = v1::UpdateContainerResourcesRequest {
            container_id: container_id.to_string(),
            linux: Some(resources),
            ..Default::default()
        };
        self.runtime
            .update_container_resources(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "UpdateContainerResources",
                source: Box::new(source),
            })?;
        Ok(())
    }

    /// Fetch a container's status.
    pub async fn container_status(
        &mut self,
        container_id: &str,
        verbose: bool,
    ) -> Result<v1::ContainerStatusResponse> {
        let request = v1::ContainerStatusRequest {
            container_id: container_id.to_string(),
            verbose,
        };
        let resp = self
            .runtime
            .container_status(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "ContainerStatus",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner())
    }

    // ---- Listing / reconciliation ------------------------------------------

    /// List containers, optionally filtered (by id, sandbox, state, labels).
    pub async fn list_containers(
        &mut self,
        filter: Option<v1::ContainerFilter>,
    ) -> Result<Vec<v1::Container>> {
        let request = v1::ListContainersRequest { filter };
        let resp = self
            .runtime
            .list_containers(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "ListContainers",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().containers)
    }

    /// List pod sandboxes, optionally filtered.
    pub async fn list_pod_sandbox(
        &mut self,
        filter: Option<v1::PodSandboxFilter>,
    ) -> Result<Vec<v1::PodSandbox>> {
        let request = v1::ListPodSandboxRequest { filter };
        let resp = self
            .runtime
            .list_pod_sandbox(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "ListPodSandbox",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().items)
    }

    /// Node-level runtime status (readiness conditions, handlers, features).
    /// The kubelet uses this to report the node's container-runtime health.
    pub async fn runtime_status(&mut self, verbose: bool) -> Result<v1::StatusResponse> {
        let request = v1::StatusRequest { verbose };
        let resp = self
            .runtime
            .status(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "Status",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner())
    }

    // ---- Stats (eviction / metrics) ----------------------------------------

    /// Per-container resource stats; `None` if the container is gone.
    pub async fn container_stats(
        &mut self,
        container_id: &str,
    ) -> Result<Option<v1::ContainerStats>> {
        let request = v1::ContainerStatsRequest {
            container_id: container_id.to_string(),
        };
        let resp = self
            .runtime
            .container_stats(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "ContainerStats",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().stats)
    }

    /// Stats for all matching containers; the kubelet's eviction manager polls
    /// this to compare usage against thresholds.
    pub async fn list_container_stats(
        &mut self,
        filter: Option<v1::ContainerStatsFilter>,
    ) -> Result<Vec<v1::ContainerStats>> {
        let request = v1::ListContainerStatsRequest { filter };
        let resp = self
            .runtime
            .list_container_stats(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "ListContainerStats",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().stats)
    }

    // ---- Exec / attach / port-forward / logs -------------------------------

    /// Run a command in a container and wait for it to finish, returning its
    /// stdout, stderr and exit code. This is the workhorse for `exec` liveness
    /// and readiness probes. `timeout` is in seconds (0 = no timeout).
    pub async fn exec_sync(
        &mut self,
        container_id: &str,
        cmd: &[&str],
        timeout: i64,
    ) -> Result<v1::ExecSyncResponse> {
        let request = v1::ExecSyncRequest {
            container_id: container_id.to_string(),
            cmd: cmd.iter().map(|s| (*s).to_string()).collect(),
            timeout,
        };
        let resp = self
            .runtime
            .exec_sync(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "ExecSync",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner())
    }

    /// Prepare a streaming `exec` session, returning the URL the kubelet's
    /// streaming proxy connects to for an interactive `kubectl exec`.
    pub async fn exec(&mut self, request: v1::ExecRequest) -> Result<String> {
        let resp = self
            .runtime
            .exec(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "Exec",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().url)
    }

    /// Prepare a streaming `attach` session, returning its URL.
    pub async fn attach(&mut self, request: v1::AttachRequest) -> Result<String> {
        let resp = self
            .runtime
            .attach(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "Attach",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().url)
    }

    /// Prepare a `port-forward` session to a sandbox, returning its URL.
    pub async fn port_forward(&mut self, pod_sandbox_id: &str, ports: &[i32]) -> Result<String> {
        let request = v1::PortForwardRequest {
            pod_sandbox_id: pod_sandbox_id.to_string(),
            port: ports.to_vec(),
        };
        let resp = self
            .runtime
            .port_forward(request)
            .await
            .map_err(|source| CriError::Rpc {
                rpc: "PortForward",
                source: Box::new(source),
            })?;
        Ok(resp.into_inner().url)
    }
}

/// Strip a `unix://` (or `unix:`) scheme from a socket path, leaving a bare
/// filesystem path for `UnixStream::connect`.
fn normalize_socket_path(socket: &Path) -> PathBuf {
    let s = socket.to_string_lossy();
    let trimmed = s
        .strip_prefix("unix://")
        .or_else(|| s.strip_prefix("unix:"))
        .unwrap_or(&s);
    PathBuf::from(trimmed)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_unix_scheme() {
        assert_eq!(
            normalize_socket_path(Path::new("unix:///run/containerd/containerd.sock")),
            PathBuf::from("/run/containerd/containerd.sock")
        );
        assert_eq!(
            normalize_socket_path(Path::new("unix:/run/foo.sock")),
            PathBuf::from("/run/foo.sock")
        );
        assert_eq!(
            normalize_socket_path(Path::new("/run/bare.sock")),
            PathBuf::from("/run/bare.sock")
        );
    }

    /// The generated client types exist and the version request is constructible.
    /// Pure compile/smoke check — no socket required.
    #[test]
    fn generated_types_present() {
        let req = v1::VersionRequest {
            version: "v1".to_string(),
        };
        assert_eq!(req.version, "v1");
    }

    /// Socket-gated live handshake. Skips unless RUSTERNETES_CRI_SOCKET points at
    /// a real CRI runtime — keeps `cargo test` green on machines without one.
    #[tokio::test]
    async fn version_handshake_against_real_runtime() {
        let Ok(socket) = std::env::var("RUSTERNETES_CRI_SOCKET") else {
            eprintln!("RUSTERNETES_CRI_SOCKET unset; skipping live CRI handshake");
            return;
        };
        let mut client = CriClient::connect(&socket)
            .await
            .expect("connect to CRI socket");
        let v = client.version().await.expect("CRI Version handshake");
        eprintln!(
            "CRI runtime: {} {} (api {})",
            v.runtime_name, v.runtime_version, v.version
        );
        assert!(!v.version.is_empty());
    }
}
