#!/usr/bin/env bash
# Generate the thin per-SIG workflow files from ci/conformance/sigs.json.
# Each emitted .github/workflows/conformance-sig-<name>.yml is a ~30-line caller
# that invokes the reusable .github/workflows/conformance-sig.yml engine. This
# keeps the SIG set config-driven: add/rename a SIG in sigs.json, re-run this,
# and scripts/tests/test-sig-workflows-sync.sh guards against drift.
#
# Usage:
#   bash scripts/gen-sig-workflows.sh              # write the files
#   bash scripts/gen-sig-workflows.sh --out DIR    # write to DIR instead (test)
#
# The output is deterministic (order follows sigs.json) so a regenerate+diff is
# a reliable drift check.
set -euo pipefail
IFS=$'\n\t'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"
MANIFEST="$REPO_ROOT/ci/conformance/sigs.json"
OUT_DIR="$REPO_ROOT/.github/workflows"

die() { echo "[gen-sig-workflows] ERROR: $*" >&2; exit 2; }
while [[ $# -gt 0 ]]; do
    case "$1" in
        --out) [[ $# -ge 2 ]] || die "--out requires a value"; OUT_DIR="$2"; shift 2 ;;
        -h|--help) sed -nE '/^# /,/^$/ s/^# ?//p' "${BASH_SOURCE[0]}" | head -20; exit 0 ;;
        *) die "unknown flag: $1" ;;
    esac
done

command -v jq >/dev/null 2>&1 || die "jq required"
[ -f "$MANIFEST" ] || die "sigs manifest not found: $MANIFEST"
mkdir -p "$OUT_DIR"

emit_one() {
    local sig="$1" idx="$2"
    # Nightly at 02:xx UTC, staggered per SIG (minute = idx*6, before the 03:00
    # node-conformance / 05:00 feature-conformance jobs that share the pool). A
    # full SIG run is heavy (up to the 300-min ceiling) and the shared
    # arc-runner-set-conformance pool is ~1 DinD/node, so per-publish fan-out
    # (9 jobs every merge) queued for hours and every run hit the job timeout
    # (#1616) — nightly + stagger caps it at 9 jobs/day that drain overnight.
    local cron_min=$(( (idx * 6) % 60 ))
    cat <<EOF
# GENERATED by scripts/gen-sig-workflows.sh from ci/conformance/sigs.json.
# DO NOT EDIT — change the registry and re-run the generator instead.
name: conformance-$sig

# Independent per-SIG conformance run. Full runs fire nightly (refreshing the
# $sig badge against the latest main image); workflow_dispatch with a \`focus\`
# runs one named test to prove a PR (that focused run does NOT touch the badge).
# All logic lives in the reusable .github/workflows/conformance-sig.yml engine.
on:
  schedule:
    - cron: '$cron_min 2 * * *'
  workflow_dispatch:
    inputs:
      focus:
        description: "Ginkgo --focus override (narrow to one test to prove a PR). Empty = full SIG run."
        required: false
        default: ''
      image-tag:
        description: "GHCR image tag to test (default main). Empty = build locally."
        required: false
        default: main

# Per-SIG group so a newer run supersedes an older one for THIS sig without
# cancelling other SIGs' runs (independence: FR-003).
concurrency:
  group: conformance-$sig
  cancel-in-progress: true

jobs:
  run:
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/conformance-sig.yml
    with:
      sig: $sig
      focus: \${{ github.event.inputs.focus || '' }}
      image-tag: \${{ github.event.inputs.image-tag || 'main' }}
EOF
}

count=0
while IFS= read -r sig; do
    [ -n "$sig" ] || continue
    emit_one "$sig" "$count" > "$OUT_DIR/conformance-$sig.yml"
    count=$((count + 1))
done < <(jq -r '.[].name' "$MANIFEST")

echo "[gen-sig-workflows] wrote $count workflow(s) to $OUT_DIR"
