#!/usr/bin/env bash
# Generate the thin per-target workflow files from ci/conformance/targets.json.
# Each emitted .github/workflows/conformance-<name>.yml is a ~30-line caller that
# invokes the reusable .github/workflows/conformance-target.yml engine. This
# keeps the target set config-driven: add/rename a target in targets.json,
# re-run this, and scripts/tests/test-target-workflows-sync.sh guards drift.
#
# A "target" is a SIG's [Conformance] slice (kind: sig) or a curated feature
# focus (kind: feature). Both run through the identical caller + engine; kind
# does not affect the generated workflow.
#
# Usage:
#   bash scripts/gen-target-workflows.sh              # write the files
#   bash scripts/gen-target-workflows.sh --out DIR    # write to DIR instead (test)
#
# The output is deterministic (order follows targets.json) so a regenerate+diff
# is a reliable drift check. Every generated file carries the GENERATED_MARKER
# line below so the sync test can identify generated workflows unambiguously.
set -euo pipefail
IFS=$'\n\t'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"
MANIFEST="$REPO_ROOT/ci/conformance/targets.json"
OUT_DIR="$REPO_ROOT/.github/workflows"

# The exact marker line stamped into every generated file. The sync test greps
# for it to enumerate generated workflows (so it never mistakes a hand-written
# conformance-*.yml — node-conformance, conformance-target, conformance-validate
# — for a generated per-target file).
GENERATED_MARKER="# GENERATED by scripts/gen-target-workflows.sh from ci/conformance/targets.json."

die() { echo "[gen-target-workflows] ERROR: $*" >&2; exit 2; }
while [[ $# -gt 0 ]]; do
    case "$1" in
        --out) [[ $# -ge 2 ]] || die "--out requires a value"; OUT_DIR="$2"; shift 2 ;;
        --print-marker) echo "$GENERATED_MARKER"; exit 0 ;;
        -h|--help) sed -nE '/^# /,/^$/ s/^# ?//p' "${BASH_SOURCE[0]}" | head -22; exit 0 ;;
        *) die "unknown flag: $1" ;;
    esac
done

command -v jq >/dev/null 2>&1 || die "jq required"
[ -f "$MANIFEST" ] || die "targets manifest not found: $MANIFEST"
mkdir -p "$OUT_DIR"

emit_one() {
    local target="$1" idx="$2"
    # Nightly at 02:xx UTC, staggered per target (minute = idx*6) so the runs
    # don't stampede the shared arc-runner-set-conformance pool (~1 DinD/node) —
    # a per-publish fan-out queued for hours and every run hit the job timeout
    # (#1616). Nightly + stagger caps it at N jobs/day that drain overnight.
    local cron_min=$(( (idx * 6) % 60 ))
    cat <<EOF
$GENERATED_MARKER
# DO NOT EDIT — change the registry and re-run the generator instead.
name: conformance-$target

# Independent per-target conformance run. Full runs fire nightly (refreshing the
# $target badge against the latest main image); workflow_dispatch with a \`focus\`
# runs one named test to prove a PR (that focused run does NOT touch the badge).
# All logic lives in the reusable .github/workflows/conformance-target.yml engine.
on:
  schedule:
    - cron: '$cron_min 2 * * *'
  workflow_dispatch:
    inputs:
      focus:
        description: "Ginkgo --focus override (narrow to one test to prove a PR). Empty = full target run."
        required: false
        default: ''
      image-tag:
        description: "GHCR image tag to test (default main). Empty = build locally."
        required: false
        default: main

# Per-target group so a newer run supersedes an older one for THIS target
# without cancelling other targets' runs (independence: FR-003).
concurrency:
  group: conformance-$target
  cancel-in-progress: true

jobs:
  run:
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/conformance-target.yml
    with:
      target: $target
      focus: \${{ github.event.inputs.focus || '' }}
      image-tag: \${{ github.event.inputs.image-tag || 'main' }}
EOF
}

count=0
while IFS= read -r target; do
    [ -n "$target" ] || continue
    emit_one "$target" "$count" > "$OUT_DIR/conformance-$target.yml"
    count=$((count + 1))
done < <(jq -r '.[].name' "$MANIFEST")

echo "[gen-target-workflows] wrote $count workflow(s) to $OUT_DIR"
