#!/usr/bin/env python3
"""Generate crates/protobuf/src/plain_zero_scalars.rs from upstream types.go.

Why: Go's generated protobuf marshaller writes every non-pointer scalar, zero
included (e.g. `dAtA[i] = 0` for `Stdin bool`), while the type's JSON tag is
`omitempty` and drops it. The decoder must emit the JSON form (absent), so it
needs the set of `(message, field)` pairs that are plain (non-pointer)
`bool`/`int*` scalars tagged `omitempty` (#2449, #2931).

Source of truth (release-1.35), every `types.go` in:
  staging/src/k8s.io/api/*/{v1,v2}/
  staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/
  staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/

Named scalar types (`type X int32`) are resolved. A field is emitted only when
EVERY same-named struct across those packages tags it plain+omitempty, so a
message name shared by two packages can never wrongly drop a field.

Usage:
  scripts/gen-protobuf-plain-zero-scalars.py            # rewrite the .rs file
  scripts/gen-protobuf-plain-zero-scalars.py --stdout   # print, do not write
Env: K8S_SRC=<path to a kubernetes checkout> (default: ../kubernetes next to
the repo, or any ancestor's sibling `kubernetes`).
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "crates/protobuf/src/plain_zero_scalars.rs")

# Pointer-to-string fields (`*string`, `*StringAlias`) are the dual case (#2952):
# Go's marshaller writes a non-nil pointer even when it is empty, so an
# explicit "" (e.g. PVC storageClassName: "") is a real value that must survive
# decode. Plain strings stay dropped when empty (the JSON twin omits them).
SCALARS = {"bool", "int", "int8", "int16", "int32", "int64",
           "uint", "uint8", "uint16", "uint32", "uint64"}

GLOBS = [
    "k8s.io/api/*/v1/types.go",
    "k8s.io/api/*/v2/types.go",
    "k8s.io/apimachinery/pkg/apis/meta/v1/types.go",
    "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go",
    "k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go",
]


def find_src():
    env = os.environ.get("K8S_SRC")
    cands = [env] if env else []
    d = ROOT
    while True:
        cands.append(os.path.join(d, "kubernetes"))
        nd = os.path.dirname(d)
        if nd == d:
            break
        d = nd
    for c in cands:
        if c and os.path.isdir(os.path.join(c, "staging/src/k8s.io/api")):
            return os.path.join(c, "staging/src")
    return None


STRUCT = re.compile(r"^type (\w+) struct \{$")
ALIAS = re.compile(r"^type (\w+) (\w+)$")
FIELD = re.compile(r'^\t(\w+)\s+(\S+)\s+`json:"([^"]*)"')


def scan(path, table, seen, ptr=None):
    """table: msg -> {json field -> all-definitions-plain-omitempty}."""
    text = open(path, encoding="utf-8").read().splitlines()
    aliases = {}
    str_aliases = {"string"}
    for line in text:
        m = ALIAS.match(line)
        if m and m.group(2) in SCALARS:
            aliases[m.group(1)] = m.group(2)
        if m and m.group(2) == "string":
            str_aliases.add(m.group(1))
    cur = None
    for line in text:
        m = STRUCT.match(line)
        if m:
            cur = m.group(1)
            seen.setdefault(cur, set())
            continue
        if line == "}":
            cur = None
            continue
        if cur is None:
            continue
        f = FIELD.match(line)
        if not f:
            continue
        typ, tag = f.group(2), f.group(3)
        parts = tag.split(",")
        name = parts[0]
        if name in ("", "-"):
            continue  # inline / skipped
        plain = (typ in SCALARS or typ in aliases) and "omitempty" in parts[1:]
        # Resolve aliases declared in other files of the package lazily: a
        # same-package alias defined in another file is rare; types.go holds
        # them all for the packages listed in GLOBS.
        if ptr is not None:
            is_ptr = typ.startswith("*") and typ[1:] in str_aliases
            ptr.setdefault(cur, {})
            pp = ptr[cur].get(name)
            ptr[cur][name] = is_ptr if pp is None else (pp and is_ptr)
        table.setdefault(cur, {})
        prev = table[cur].get(name)
        table[cur][name] = plain if prev is None else (prev and plain)


def generate(src):
    table = {}
    ptr = {}
    seen = {}
    files = []
    for g in GLOBS:
        files += sorted(glob.glob(os.path.join(src, g)))
    if not files:
        sys.exit("no types.go found under " + src)
    for p in files:
        scan(p, table, seen, ptr)
    rows = []
    for msg in sorted(table):
        fields = sorted(f for f, ok in table[msg].items() if ok)
        if fields:
            rows.append((msg, fields))
    prows = []
    for msg in sorted(ptr):
        fields = sorted(f for f, ok in ptr[msg].items() if ok)
        if fields:
            prows.append((msg, fields))
    out = []
    out.append("// @generated by scripts/gen-protobuf-plain-zero-scalars.py -- DO NOT EDIT.")
    out.append("// Source: k8s.io/api, apimachinery meta/v1, apiextensions v1, apiregistration v1")
    out.append("// `types.go` at kubernetes release-1.35. Regenerate with:")
    out.append("//   scripts/gen-protobuf-plain-zero-scalars.py")
    out.append("// A test (tests/plain_zero_scalars_table.rs) fails when this drifts.")
    out.append("")
    out.append("/// Non-pointer `bool`/`int*` fields tagged `json:\",omitempty\"` upstream,")
    out.append("/// by message name, sorted by name (binary-searched by the decoder).")
    out.append("#[rustfmt::skip]")
    out.append("pub const PLAIN_ZERO_SCALARS: &[(&str, &[&str])] = &[")
    for msg, fields in rows:
        out.append("    (")
        out.append('        "%s",' % msg)
        out.append("        &[" + ", ".join('"%s"' % f for f in fields) + "],")
        out.append("    ),")
    out.append("];")
    out.append("")
    out.append("/// Pointer-to-string (`*string`, `*StringAlias`) fields upstream, by message")
    out.append("/// name, sorted by name. An explicit empty value is real for these (#2952).")
    out.append("#[rustfmt::skip]")
    out.append("pub const POINTER_STRINGS: &[(&str, &[&str])] = &[")
    for msg, fields in prows:
        out.append("    (")
        out.append('        "%s",' % msg)
        out.append("        &[" + ", ".join('"%s"' % f for f in fields) + "],")
        out.append("    ),")
    out.append("];")
    out.append("")
    return "\n".join(out)


def main():
    src = find_src()
    if not src:
        sys.exit("kubernetes checkout not found (set K8S_SRC)")
    text = generate(src)
    if "--stdout" in sys.argv:
        sys.stdout.write(text)
    else:
        with open(OUT, "w", encoding="utf-8") as fh:
            fh.write(text)
        print("wrote", OUT)


if __name__ == "__main__":
    main()
