#!/usr/bin/env bash
# Generate the thin per-module vanilla-swap workflow files from
# ci/vanilla-swap/targets.json. Each emitted
# .github/workflows/vanilla-swap-<module>.yml is a ~30-line caller that invokes
# the reusable .github/workflows/vanilla-swap-module.yml engine.
#
# One workflow per module — never a matrix. A matrix puts five modules in ONE
# workflow run, so the run's status (and its badge) is the AND of five
# unrelated isolation tests, a queued-but-unstarted module is indistinguishable
# from a passing one, and re-running "just the kubelet" means re-running the
# whole matrix. Separate workflows give each module its own status, its own
# badge, its own concurrency group, and its own dispatch button.
# Mirrors scripts/gen-target-workflows.sh (per-target conformance).
#
# Usage:
#   bash scripts/gen-vanilla-swap-workflows.sh              # write the files
#   bash scripts/gen-vanilla-swap-workflows.sh --out DIR    # write to DIR (test)
#
# The output is deterministic (order follows targets.json) so a regenerate+diff
# is a reliable drift check — scripts/tests/test-vanilla-swap-workflows-sync.sh.
set -euo pipefail
IFS=$'\n\t'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"
MANIFEST="$REPO_ROOT/ci/vanilla-swap/targets.json"
OUT_DIR="$REPO_ROOT/.github/workflows"

# The exact marker line stamped into every generated file. The sync test greps
# for it to enumerate generated workflows, so a hand-written vanilla-swap-*.yml
# (vanilla-swap-module.yml, the engine) is never mistaken for a generated one.
GENERATED_MARKER="# GENERATED by scripts/gen-vanilla-swap-workflows.sh from ci/vanilla-swap/targets.json."

die() { echo "[gen-vanilla-swap-workflows] ERROR: $*" >&2; exit 2; }
while [[ $# -gt 0 ]]; do
    case "$1" in
        --out) [[ $# -ge 2 ]] || die "--out requires a value"; OUT_DIR="$2"; shift 2 ;;
        --print-marker) echo "$GENERATED_MARKER"; exit 0 ;;
        -h|--help) sed -nE '/^# /,/^$/ s/^# ?//p' "${BASH_SOURCE[0]}" | head -22; exit 0 ;;
        *) die "unknown flag: $1" ;;
    esac
done

command -v jq >/dev/null 2>&1 || die "jq required"
[ -f "$MANIFEST" ] || die "vanilla-swap manifest not found: $MANIFEST"
mkdir -p "$OUT_DIR"

emit_one() {
    local module="$1" idx="$2"
    # Nightly, staggered 2h apart starting 04:00 UTC. Each swap run brings up a
    # kind cluster and can take the full 90-minute budget, and the shared
    # arc-runner-set-conformance pool fits ~1 DinD job per node — firing all
    # five at 04:00 (the old matrix) queued them behind each other anyway, just
    # invisibly. Spreading them keeps each run's queue time near zero.
    local cron_hour=$(( (4 + idx * 2) % 24 ))
    cat <<EOF
$GENERATED_MARKER
# DO NOT EDIT — change the registry and re-run the generator instead.
name: vanilla-swap-$module

# Independent single-module vanilla-swap run: an UNMODIFIED upstream Kubernetes
# cluster (kind) with exactly ONE rusternetes component — $module — swapped in,
# then the test subset scoped to that component. Nightly runs refresh the
# $module badge; workflow_dispatch runs it on demand.
# All logic lives in the reusable .github/workflows/vanilla-swap-module.yml engine.
on:
  schedule:
    - cron: '0 $cron_hour * * *'
  workflow_dispatch:
    inputs:
      image-tag:
        description: "GHCR rusternetes image tag to swap in (default main)."
        required: false
        default: main
      k8s-version:
        description: "Vanilla baseline Kubernetes version (default v1.35)."
        required: false
        default: v1.35

# Per-module group so a newer run supersedes an older one for THIS module
# without cancelling the other modules' runs.
concurrency:
  group: vanilla-swap-$module
  cancel-in-progress: true

jobs:
  run:
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/vanilla-swap-module.yml
    with:
      module: $module
      image-tag: \${{ github.event.inputs.image-tag || 'main' }}
      k8s-version: \${{ github.event.inputs.k8s-version || 'v1.35' }}
EOF
}

count=0
while IFS= read -r module; do
    [ -n "$module" ] || continue
    emit_one "$module" "$count" > "$OUT_DIR/vanilla-swap-$module.yml"
    count=$((count + 1))
done < <(jq -r '.[].module' "$MANIFEST")

echo "[gen-vanilla-swap-workflows] wrote $count workflow(s) to $OUT_DIR"
