#!/bin/bash

# Generate Default ServiceAccounts
# This script generates the default ServiceAccounts for default namespaces

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_step() {
    echo -e "${GREEN}==>${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}WARNING:${NC} $1"
}

# Create the ServiceAccount YAML for a namespace
create_sa_resources() {
    local namespace=$1

    cat << EOF
---
# Default ServiceAccount for $namespace namespace
# Generated by scripts/generate-default-serviceaccounts.sh
# No token Secret is created: upstream never mints one (the TokensController
# only populates Secrets a user created); pods get bound tokens via the
# kube-api-access projected volume.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: $namespace
EOF
}

# Main script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${SCRIPT_DIR}/.rusternetes/default-serviceaccounts.yaml"

print_step "Generating default ServiceAccounts..."

# Create .rusternetes directory if it doesn't exist
mkdir -p "${SCRIPT_DIR}/.rusternetes"

# Generate the YAML file
{
    echo "# Default ServiceAccounts"
    echo "# Generated by scripts/generate-default-serviceaccounts.sh"
    echo "# This file is automatically created during cluster bootstrap"
    echo ""
    create_sa_resources "default"
    create_sa_resources "kube-system"
} > "$OUTPUT_FILE"

print_step "Generated ServiceAccounts saved to: $OUTPUT_FILE"
echo ""
print_warning "It is automatically created during bootstrap and is .gitignored"
echo ""
echo "To apply these resources:"
echo "  export KUBECONFIG=.rusternetes/kubeconfig"
echo "  ./target/release/kubectl apply -f $OUTPUT_FILE"
echo ""
