//! Legacy secret-based service-account token observations (#2757).
//!
//! Ported from `pkg/serviceaccount/legacy.go:143-170` (audit annotations
//! `authentication.k8s.io/legacy-token-{autogenerated-secret,manual-secret,
//! invalidated}`, `warning.AddWarning`, the `legacy_*_uses_total` counters)
//! and `pkg/serviceaccount/jwt.go:383-387` (`legacy-token` annotation and
//! `legacy_tokens_total` for a token without an audience).

use base64::Engine;
use rusternetes_common::auth::{ServiceAccountClaims, LEGACY_ISSUER};
use rusternetes_middleware::{
    serviceaccount_metrics, validate_service_account_token, AuthObservations,
};
use rusternetes_storage::{build_key, Storage, StorageBackend};
use serde_json::{json, Value};

const INVALID_SINCE: &str = "kubernetes.io/legacy-token-invalid-since";
const AUTO_WARNING: &str = "Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.";

fn token() -> String {
    let b64 = |v: &Value| {
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(serde_json::to_vec(v).unwrap())
    };
    let payload = json!({
        "iss": LEGACY_ISSUER,
        "sub": "system:serviceaccount:ns:sa",
        "kubernetes.io/serviceaccount/namespace": "ns",
        "kubernetes.io/serviceaccount/service-account.name": "sa",
        "kubernetes.io/serviceaccount/service-account.uid": "sa-uid",
        "kubernetes.io/serviceaccount/secret.name": "tok",
    });
    format!("{}.{}.sig", b64(&json!({"alg": "HS256"})), b64(&payload))
}

fn claims() -> ServiceAccountClaims {
    serde_json::from_value(json!({
        "iss": LEGACY_ISSUER,
        "sub": "system:serviceaccount:ns:sa",
        "namespace": "ns",
        "uid": "sa-uid",
    }))
    .unwrap()
}

async fn seed(sa_secrets: &[&str], labels: Value) -> StorageBackend {
    let s = StorageBackend::new_memory();
    let refs: Vec<Value> = sa_secrets.iter().map(|n| json!({"name": n})).collect();
    s.create(
        &build_key("serviceaccounts", Some("ns"), "sa"),
        &json!({"apiVersion": "v1", "kind": "ServiceAccount",
                "metadata": {"name": "sa", "namespace": "ns", "uid": "sa-uid"},
                "secrets": refs}),
    )
    .await
    .unwrap();
    s.create(
        &build_key("secrets", Some("ns"), "tok"),
        &json!({"apiVersion": "v1", "kind": "Secret",
                "type": "kubernetes.io/service-account-token",
                "metadata": {"name": "tok", "namespace": "ns", "uid": "sec-uid",
                             "labels": labels},
                "data": {"token": base64::engine::general_purpose::STANDARD.encode(token())}}),
    )
    .await
    .unwrap();
    s
}

fn has(obs: &AuthObservations, k: &str, v: &str) -> bool {
    obs.audit_annotations
        .iter()
        .any(|(ak, av)| ak == k && av == v)
}

#[tokio::test]
async fn auto_generated_token_warns_annotates_and_counts() {
    let s = seed(&["tok"], json!({})).await;
    let m = serviceaccount_metrics();
    let (legacy, auto) = (
        m.legacy_tokens_total.get(),
        m.legacy_auto_token_uses_total.get(),
    );
    let mut obs = AuthObservations::default();
    validate_service_account_token(&s, &token(), &claims(), &mut obs)
        .await
        .unwrap();
    // jwt.go:385: a token with no audience
    assert!(has(
        &obs,
        "authentication.k8s.io/legacy-token",
        "system:serviceaccount:ns:sa"
    ));
    // legacy.go:158-162
    assert!(has(
        &obs,
        "authentication.k8s.io/legacy-token-autogenerated-secret",
        "tok"
    ));
    assert_eq!(obs.warnings, vec![AUTO_WARNING.to_string()]);
    assert!(m.legacy_tokens_total.get() > legacy);
    assert!(m.legacy_auto_token_uses_total.get() > auto);
}

#[tokio::test]
async fn manual_token_annotates_and_counts_without_warning() {
    let s = seed(&[], json!({})).await;
    let m = serviceaccount_metrics();
    let manual = m.legacy_manual_token_uses_total.get();
    let mut obs = AuthObservations::default();
    validate_service_account_token(&s, &token(), &claims(), &mut obs)
        .await
        .unwrap();
    // legacy.go:165-168
    assert!(has(
        &obs,
        "authentication.k8s.io/legacy-token-manual-secret",
        "tok"
    ));
    assert!(!obs
        .audit_annotations
        .iter()
        .any(|(k, _)| k.ends_with("autogenerated-secret")));
    assert!(obs.warnings.is_empty());
    assert!(m.legacy_manual_token_uses_total.get() > manual);
}

#[tokio::test]
async fn invalidated_token_annotates_and_counts() {
    let s = seed(&["tok"], json!({ INVALID_SINCE: "2022-12-20" })).await;
    let m = serviceaccount_metrics();
    let invalid = m.invalid_legacy_auto_token_uses_total.get();
    let mut obs = AuthObservations::default();
    let err = validate_service_account_token(&s, &token(), &claims(), &mut obs)
        .await
        .unwrap_err();
    assert!(err.contains("has been marked invalid"));
    // legacy.go:150 `secret.Name+"/"+secret.Namespace`
    assert!(has(
        &obs,
        "authentication.k8s.io/legacy-token-invalidated",
        "tok/ns"
    ));
    assert!(m.invalid_legacy_auto_token_uses_total.get() > invalid);
}

#[tokio::test]
async fn bound_token_with_an_audience_is_not_a_legacy_use() {
    let s = StorageBackend::new_memory();
    let mut c = claims();
    c.iss = "https://kubernetes.default.svc".to_string();
    c.aud = vec!["api".to_string()];
    // fails on the missing SA, but must not record a legacy observation
    let mut obs = AuthObservations::default();
    let _ = validate_service_account_token(&s, "x.y.z", &c, &mut obs).await;
    assert!(obs.audit_annotations.is_empty());
    assert!(obs.warnings.is_empty());
}
