// @generated by scripts/gen-protobuf-plain-zero-scalars.py -- DO NOT EDIT.
// Source: k8s.io/api, apimachinery meta/v1, apiextensions v1, apiregistration v1
// `types.go` at kubernetes release-1.35. Regenerate with:
//   scripts/gen-protobuf-plain-zero-scalars.py
// A test (tests/plain_zero_scalars_table.rs) fails when this drifts.

/// Non-pointer `bool`/`int*` fields tagged `json:",omitempty"` upstream,
/// by message name, sorted by name (binary-searched by the decoder).
#[rustfmt::skip]
pub(crate) const PLAIN_ZERO_SCALARS: &[(&str, &[&str])] = &[
    (
        "APIServiceSpec",
        &["insecureSkipTLSVerify"],
    ),
    (
        "AWSElasticBlockStoreVolumeSource",
        &["partition", "readOnly"],
    ),
    (
        "AzureFilePersistentVolumeSource",
        &["readOnly"],
    ),
    (
        "AzureFileVolumeSource",
        &["readOnly"],
    ),
    (
        "CSIPersistentVolumeSource",
        &["readOnly"],
    ),
    (
        "CephFSPersistentVolumeSource",
        &["readOnly"],
    ),
    (
        "CephFSVolumeSource",
        &["readOnly"],
    ),
    (
        "CinderPersistentVolumeSource",
        &["readOnly"],
    ),
    (
        "CinderVolumeSource",
        &["readOnly"],
    ),
    (
        "Condition",
        &["observedGeneration"],
    ),
    (
        "Container",
        &["stdin", "stdinOnce", "tty"],
    ),
    (
        "ContainerImage",
        &["sizeBytes"],
    ),
    (
        "ContainerPort",
        &["hostPort"],
    ),
    (
        "ContainerStateTerminated",
        &["signal"],
    ),
    (
        "CustomResourceColumnDefinition",
        &["priority"],
    ),
    (
        "CustomResourceDefinitionCondition",
        &["observedGeneration"],
    ),
    (
        "CustomResourceDefinitionSpec",
        &["preserveUnknownFields"],
    ),
    (
        "CustomResourceDefinitionStatus",
        &["observedGeneration"],
    ),
    (
        "CustomResourceDefinitionVersion",
        &["deprecated"],
    ),
    (
        "DaemonSetSpec",
        &["minReadySeconds"],
    ),
    (
        "DaemonSetStatus",
        &["numberAvailable", "numberUnavailable", "observedGeneration", "updatedNumberScheduled"],
    ),
    (
        "DeploymentSpec",
        &["minReadySeconds", "paused"],
    ),
    (
        "DeploymentStatus",
        &["availableReplicas", "observedGeneration", "readyReplicas", "replicas", "unavailableReplicas", "updatedReplicas"],
    ),
    (
        "DeviceSubRequest",
        &["count"],
    ),
    (
        "EphemeralContainerCommon",
        &["stdin", "stdinOnce", "tty"],
    ),
    (
        "Event",
        &["count", "deprecatedCount"],
    ),
    (
        "ExactDeviceRequest",
        &["count"],
    ),
    (
        "FCVolumeSource",
        &["readOnly"],
    ),
    (
        "FlexPersistentVolumeSource",
        &["readOnly"],
    ),
    (
        "FlexVolumeSource",
        &["readOnly"],
    ),
    (
        "GCEPersistentDiskVolumeSource",
        &["partition", "readOnly"],
    ),
    (
        "GlusterfsPersistentVolumeSource",
        &["readOnly"],
    ),
    (
        "GlusterfsVolumeSource",
        &["readOnly"],
    ),
    (
        "ISCSIPersistentVolumeSource",
        &["chapAuthDiscovery", "chapAuthSession", "readOnly"],
    ),
    (
        "ISCSIVolumeSource",
        &["chapAuthDiscovery", "chapAuthSession", "readOnly"],
    ),
    (
        "JobStatus",
        &["active", "failed", "succeeded"],
    ),
    (
        "ListOptions",
        &["allowWatchBookmarks", "limit", "watch"],
    ),
    (
        "NFSVolumeSource",
        &["readOnly"],
    ),
    (
        "NodeSpec",
        &["unschedulable"],
    ),
    (
        "ObjectMeta",
        &["generation"],
    ),
    (
        "PersistentVolumeClaimVolumeSource",
        &["readOnly"],
    ),
    (
        "PodAttachOptions",
        &["stderr", "stdin", "stdout", "tty"],
    ),
    (
        "PodCondition",
        &["observedGeneration"],
    ),
    (
        "PodDisruptionBudgetStatus",
        &["observedGeneration"],
    ),
    (
        "PodExecOptions",
        &["stderr", "stdin", "stdout", "tty"],
    ),
    (
        "PodLogOptions",
        &["follow", "insecureSkipTLSVerifyBackend", "previous", "timestamps"],
    ),
    (
        "PodSpec",
        &["hostIPC", "hostNetwork", "hostPID"],
    ),
    (
        "PodStatus",
        &["observedGeneration"],
    ),
    (
        "PortworxVolumeSource",
        &["readOnly"],
    ),
    (
        "PriorityClass",
        &["globalDefault"],
    ),
    (
        "Probe",
        &["failureThreshold", "initialDelaySeconds", "periodSeconds", "successThreshold", "timeoutSeconds"],
    ),
    (
        "QuobyteVolumeSource",
        &["readOnly"],
    ),
    (
        "RBDPersistentVolumeSource",
        &["readOnly"],
    ),
    (
        "RBDVolumeSource",
        &["readOnly"],
    ),
    (
        "ReplicaSetSpec",
        &["minReadySeconds"],
    ),
    (
        "ReplicaSetStatus",
        &["availableReplicas", "fullyLabeledReplicas", "observedGeneration", "readyReplicas"],
    ),
    (
        "ReplicationControllerSpec",
        &["minReadySeconds"],
    ),
    (
        "ReplicationControllerStatus",
        &["availableReplicas", "fullyLabeledReplicas", "observedGeneration", "readyReplicas"],
    ),
    (
        "ResourcePolicyRule",
        &["clusterScope"],
    ),
    (
        "ScaleIOPersistentVolumeSource",
        &["readOnly", "sslEnabled"],
    ),
    (
        "ScaleIOVolumeSource",
        &["readOnly", "sslEnabled"],
    ),
    (
        "ScaleSpec",
        &["replicas"],
    ),
    (
        "ServiceBackendPort",
        &["number"],
    ),
    (
        "ServicePort",
        &["nodePort"],
    ),
    (
        "ServiceSpec",
        &["healthCheckNodePort", "publishNotReadyAddresses"],
    ),
    (
        "StatefulSetSpec",
        &["minReadySeconds"],
    ),
    (
        "StatefulSetStatus",
        &["currentReplicas", "observedGeneration", "readyReplicas", "updatedReplicas"],
    ),
    (
        "Status",
        &["code"],
    ),
    (
        "StatusDetails",
        &["retryAfterSeconds"],
    ),
    (
        "StorageOSPersistentVolumeSource",
        &["readOnly"],
    ),
    (
        "StorageOSVolumeSource",
        &["readOnly"],
    ),
    (
        "SubjectAccessReviewStatus",
        &["denied"],
    ),
    (
        "TokenReviewStatus",
        &["authenticated"],
    ),
    (
        "ValidatingAdmissionPolicyStatus",
        &["observedGeneration"],
    ),
    (
        "VolumeMount",
        &["readOnly"],
    ),
    (
        "VolumeMountStatus",
        &["readOnly"],
    ),
];
